name: (prod) Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          extended: true

      - name: Install Theme
        uses: actions/checkout@v4
        with:
          repository: lxndrblz/anatole
          path: themes/anatole

      - name: Build
        run: hugo --minify

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: public
          retention-days: 3

  deployment:
    runs-on: ubuntu-latest
    needs: build
    name: deployment
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: public

      - name: deploy prod
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: runner
        with:
          apiToken: ${{ secrets.cf_api_token }}
          environment: prod